[functions]
external_node_modules = ["express"]
node_bundler = "webpack"
[[redirects]]
force = true
from = "/www/*"
status = 200
to = "/.netlify/functions/www/:splat"
[[headers]]
for = "/documents/*"
[headers.values]
X-Robots-Tag = "noindex"